name: Build and deploy to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

  deploy-test:
    needs: build
    environment: test
    runs-on: ubuntu-latest
    steps:
    - name: Upload to Test PyPI
      run: |
        twine upload --repository testpypi dist/*
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}

    - name: Test installation from Test PyPI
      run: |
        pip install --index-url https://test.pypi.org/simple/ pyhelmgen
      continue-on-error: true

    - name: Confirm Test PyPI installation works
      run: |
        python -c "import HelmFromComposer; print(HelmFromComposer.__version__)"

  deploy-prod:
    needs: deploy-test
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Upload to PyPI
      run: |
        twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.PROD_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PROD_PYPI_API_TOKEN }}